.PHONY: all t_0 t_1 t_2 t_3 t_4 t_5 t_6 t_7 t_8 t_9 t_10 t_11 t_12 t_13 t_14 t_15 t_16 t_17 t_18 t_19 t_20 t_21 t_22 t_23 t_24 t_25 t_26 t_27 t_28 t_29 t_30 t_31 t_32 t_33 t_34 t_35 t_36 t_37 t_38 t_39 t_40 t_41 t_42 t_43 t_44 t_45 t_46 t_47 t_48 t_49 t_50 t_51 t_52 t_53 t_54 t_55 t_56 t_57 t_58 t_59 t_60 t_61 t_62 t_63 t_64 t_65 t_66 t_67 t_68 t_69 t_70 t_71 t_72 t_73 t_74 t_75 t_76 t_77 t_78 t_79 t_80 t_81 t_82 t_83 t_84 t_85 t_86
all: t_42

CLANG ?= clang++

t_0: t_43 t_44| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/utility_0.~hdr.pcm -fmodule-file=../../../.install/pcm/cstddef_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -xc++-module --precompile ../../../src/cairn/utils/hash.cpp -o ../../../.install/pcm/cairn.utils.hash.pcm
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/utility_0.~hdr.pcm -fmodule-file=../../../.install/pcm/cstddef_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -c ../../../src/cairn/utils/hash.cpp -o ../../../.install/obj/hash_9a8dee51f130cf79.o

t_1: t_43 t_45 t_46 t_47 t_48 t_49 t_50 t_51 t_52| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/utility_0.~hdr.pcm -fmodule-file=../../../.install/pcm/type_traits_0.~hdr.pcm -fmodule-file=../../../.install/pcm/stdexcept_0.~hdr.pcm -fmodule-file=../../../.install/pcm/set_0.~hdr.pcm -fmodule-file=../../../.install/pcm/map_0.~hdr.pcm -fmodule-file=../../../.install/pcm/memory_0.~hdr.pcm -fmodule-file=../../../.install/pcm/iostream_0.~hdr.pcm -fmodule-file=../../../.install/pcm/cstdint_0.~hdr.pcm -fmodule-file=../../../.install/pcm/concepts_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -xc++-module --precompile ../../../src/cairn/utils/serializer.cpp -o ../../../.install/pcm/cairn.utils.serializer.pcm
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/utility_0.~hdr.pcm -fmodule-file=../../../.install/pcm/type_traits_0.~hdr.pcm -fmodule-file=../../../.install/pcm/stdexcept_0.~hdr.pcm -fmodule-file=../../../.install/pcm/set_0.~hdr.pcm -fmodule-file=../../../.install/pcm/map_0.~hdr.pcm -fmodule-file=../../../.install/pcm/memory_0.~hdr.pcm -fmodule-file=../../../.install/pcm/iostream_0.~hdr.pcm -fmodule-file=../../../.install/pcm/cstdint_0.~hdr.pcm -fmodule-file=../../../.install/pcm/concepts_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -c ../../../src/cairn/utils/serializer.cpp -o ../../../.install/obj/serializer_9a8dee51f130cf79.o

t_2: t_49 t_8| workdir 
	cd src/cairn/compilers/clang; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../../.install/pcm/memory_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../../.install/pcm -xc++-module --precompile ../../../../src/cairn/compilers/clang/factory.cpp -o ../../../../.install/pcm/cairn.compiler.clang.pcm
	cd src/cairn/compilers/clang; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../../.install/pcm/memory_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../../.install/pcm -c ../../../../src/cairn/compilers/clang/factory.cpp -o ../../../../.install/obj/factory_2f01e9763865527e.o

t_3: t_4 t_27 t_53 t_54 t_55 t_56 t_26 t_57 t_58 t_59 t_60 t_61 t_46 t_62 t_0| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -fmodule-file=../../.install/pcm/fstream_0.~hdr.pcm -fmodule-file=../../.install/pcm/string_view_0.~hdr.pcm -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../.install/pcm/optional_0.~hdr.pcm -fmodule-file=../../.install/pcm/cctype_0.~hdr.pcm -fmodule-file=../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../.install/pcm/system_error_0.~hdr.pcm -fmodule-file=../../.install/pcm/format_0.~hdr.pcm -fmodule-file=../../.install/pcm/stdexcept_0.~hdr.pcm -fmodule-file=../../.install/pcm/functional_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -c ../../src/cairn/module_resolver.cpp -o ../../.install/obj/module_resolver_f4ce731b09f65819.o

t_4: t_63 t_59 t_50| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/algorithm_0.~hdr.pcm -fmodule-file=../../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../../.install/pcm/iostream_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -xc++-module --precompile ../../../src/cairn/utils/utf_8.cpp -o ../../../.install/pcm/cairn.utils.utf8.pcm
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/algorithm_0.~hdr.pcm -fmodule-file=../../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../../.install/pcm/iostream_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -c ../../../src/cairn/utils/utf_8.cpp -o ../../../.install/obj/utf_8_9a8dee51f130cf79.o

t_5: t_64 t_57 t_65 t_29 t_16 t_53 t_0 t_4 t_22 t_54 t_66 t_59 t_55 t_67 t_68 t_56| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/exception_0.~hdr.pcm -fmodule-file=../../.install/pcm/optional_0.~hdr.pcm -fmodule-file=../../.install/pcm/variant_0.~hdr.pcm -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -fmodule-file=../../.install/pcm/fstream_0.~hdr.pcm -fmodule-file=../../.install/pcm/sstream_0.~hdr.pcm -fmodule-file=../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../.install/pcm/string_view_0.~hdr.pcm -fmodule-file=../../.install/pcm/ostream_0.~hdr.pcm -fmodule-file=../../.install/pcm/unordered_map_0.~hdr.pcm -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -c ../../src/cairn/compile_commands_supp.cpp -o ../../.install/obj/compile_commands_supp_f4ce731b09f65819.o

t_6: t_56 t_35 t_38 t_27 t_53 t_16| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -xc++-module --precompile ../../src/cairn/cli.cpp -o ../../.install/pcm/cairn.cli.pcm
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -c ../../src/cairn/cli.cpp -o ../../.install/obj/cli_f4ce731b09f65819.o

t_7: t_69 t_45 t_70 t_71 t_72 t_49| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/condition_variable_0.~hdr.pcm -fmodule-file=../../../.install/pcm/type_traits_0.~hdr.pcm -fmodule-file=../../../.install/pcm/queue_0.~hdr.pcm -fmodule-file=../../../.install/pcm/mutex_0.~hdr.pcm -fmodule-file=../../../.install/pcm/thread_0.~hdr.pcm -fmodule-file=../../../.install/pcm/memory_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -xc++-module --precompile ../../../src/cairn/utils/thread_pool.cpp -o ../../../.install/pcm/cairn.utils.threadpool.pcm
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/condition_variable_0.~hdr.pcm -fmodule-file=../../../.install/pcm/type_traits_0.~hdr.pcm -fmodule-file=../../../.install/pcm/queue_0.~hdr.pcm -fmodule-file=../../../.install/pcm/mutex_0.~hdr.pcm -fmodule-file=../../../.install/pcm/thread_0.~hdr.pcm -fmodule-file=../../../.install/pcm/memory_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -c ../../../src/cairn/utils/thread_pool.cpp -o ../../../.install/obj/thread_pool_9a8dee51f130cf79.o

t_8: t_73 t_56 t_31 t_33 t_16 t_29 t_36 t_19 t_53 t_10 t_15 t_12 t_27 t_34 t_55 t_61| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/span_0.~hdr.pcm -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -fmodule-file=../../.install/pcm/string_view_0.~hdr.pcm -fmodule-file=../../.install/pcm/format_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -xc++-module --precompile ../../src/cairn/abstract_compiler.cpp -o ../../.install/pcm/cairn.abstract_compiler.pcm
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/span_0.~hdr.pcm -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -fmodule-file=../../.install/pcm/string_view_0.~hdr.pcm -fmodule-file=../../.install/pcm/format_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -c ../../src/cairn/abstract_compiler.cpp -o ../../.install/obj/abstract_compiler_f4ce731b09f65819.o

t_9: t_49 t_8| workdir 
	cd src/cairn/compilers/gcc; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../../.install/pcm/memory_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../../.install/pcm -xc++-module --precompile ../../../../src/cairn/compilers/gcc/factory.cpp -o ../../../../.install/pcm/cairn.compiler.gcc.pcm
	cd src/cairn/compilers/gcc; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../../.install/pcm/memory_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../../.install/pcm -c ../../../../src/cairn/compilers/gcc/factory.cpp -o ../../../../.install/obj/factory_4b9f900a6746ec2b.o

t_10: t_56 t_53| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -xc++-module --precompile ../../src/cairn/origin_env.cpp -o ../../.install/pcm/cairn.origin_env.pcm
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -c ../../src/cairn/origin_env.cpp -o ../../.install/obj/origin_env_f4ce731b09f65819.o

t_11: t_70 t_56 t_59 t_73| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/queue_0.~hdr.pcm -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../.install/pcm/span_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -xc++-module --precompile ../../src/cairn/build_plan.cpp -o ../../.install/pcm/cairn.build_plan.pcm
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/queue_0.~hdr.pcm -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../.install/pcm/span_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -c ../../src/cairn/build_plan.cpp -o ../../.install/obj/build_plan_f4ce731b09f65819.o

t_12: t_36| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fprebuilt-module-path=../../../.install/pcm -xc++-module --precompile ../../../src/cairn/utils/process.cpp -o ../../../.install/pcm/cairn.utils.process.pcm
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fprebuilt-module-path=../../../.install/pcm -c ../../../src/cairn/utils/process.cpp -o ../../../.install/obj/process_9a8dee51f130cf79.o

t_13: t_65 t_48 t_56 t_68 t_74 t_53 t_19 t_0 t_73 t_26 t_75 t_16 t_29 t_15 t_11 t_8 t_76 t_45 t_10 t_38 t_62| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/variant_0.~hdr.pcm -fmodule-file=../../.install/pcm/map_0.~hdr.pcm -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../.install/pcm/unordered_map_0.~hdr.pcm -fmodule-file=../../.install/pcm/iterator_0.~hdr.pcm -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -fmodule-file=../../.install/pcm/span_0.~hdr.pcm -fmodule-file=../../.install/pcm/chrono_0.~hdr.pcm -fmodule-file=../../.install/pcm/atomic_0.~hdr.pcm -fmodule-file=../../.install/pcm/type_traits_0.~hdr.pcm -fmodule-file=../../.install/pcm/functional_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -xc++-module --precompile ../../src/cairn/module_database.ifc.cpp -o ../../.install/pcm/cairn.module_database.pcm
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/variant_0.~hdr.pcm -fmodule-file=../../.install/pcm/map_0.~hdr.pcm -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../.install/pcm/unordered_map_0.~hdr.pcm -fmodule-file=../../.install/pcm/iterator_0.~hdr.pcm -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -fmodule-file=../../.install/pcm/span_0.~hdr.pcm -fmodule-file=../../.install/pcm/chrono_0.~hdr.pcm -fmodule-file=../../.install/pcm/atomic_0.~hdr.pcm -fmodule-file=../../.install/pcm/type_traits_0.~hdr.pcm -fmodule-file=../../.install/pcm/functional_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -c ../../src/cairn/module_database.ifc.cpp -o ../../.install/obj/module_database.ifc_f4ce731b09f65819.o

t_14: t_77 t_63 t_78 t_68 t_57 t_56 t_59 t_53 t_73| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/array_0.~hdr.pcm -fmodule-file=../../.install/pcm/algorithm_0.~hdr.pcm -fmodule-file=../../.install/pcm/unordered_set_0.~hdr.pcm -fmodule-file=../../.install/pcm/unordered_map_0.~hdr.pcm -fmodule-file=../../.install/pcm/optional_0.~hdr.pcm -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -fmodule-file=../../.install/pcm/span_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -xc++-module --precompile ../../src/cairn/preprocess.ifc.cpp -o ../../.install/pcm/cairn.preprocess.pcm
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/array_0.~hdr.pcm -fmodule-file=../../.install/pcm/algorithm_0.~hdr.pcm -fmodule-file=../../.install/pcm/unordered_set_0.~hdr.pcm -fmodule-file=../../.install/pcm/unordered_map_0.~hdr.pcm -fmodule-file=../../.install/pcm/optional_0.~hdr.pcm -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -fmodule-file=../../.install/pcm/span_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -c ../../src/cairn/preprocess.ifc.cpp -o ../../.install/obj/preprocess.ifc_f4ce731b09f65819.o

t_15: t_53 t_59 t_56 t_63 t_19| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -fmodule-file=../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../.install/pcm/algorithm_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -xc++-module --precompile ../../src/cairn/scanner.cpp -o ../../.install/pcm/cairn.source_scanner.pcm
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -fmodule-file=../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../.install/pcm/algorithm_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -c ../../src/cairn/scanner.cpp -o ../../.install/obj/scanner_f4ce731b09f65819.o

t_16: t_50 t_73 t_53 t_65 t_63 t_55 t_59| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/iostream_0.~hdr.pcm -fmodule-file=../../../.install/pcm/span_0.~hdr.pcm -fmodule-file=../../../.install/pcm/filesystem_0.~hdr.pcm -fmodule-file=../../../.install/pcm/variant_0.~hdr.pcm -fmodule-file=../../../.install/pcm/algorithm_0.~hdr.pcm -fmodule-file=../../../.install/pcm/string_view_0.~hdr.pcm -fmodule-file=../../../.install/pcm/string_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -xc++-module --precompile ../../../src/cairn/utils/arguments.cpp -o ../../../.install/pcm/cairn.utils.arguments.pcm
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/iostream_0.~hdr.pcm -fmodule-file=../../../.install/pcm/span_0.~hdr.pcm -fmodule-file=../../../.install/pcm/filesystem_0.~hdr.pcm -fmodule-file=../../../.install/pcm/variant_0.~hdr.pcm -fmodule-file=../../../.install/pcm/algorithm_0.~hdr.pcm -fmodule-file=../../../.install/pcm/string_view_0.~hdr.pcm -fmodule-file=../../../.install/pcm/string_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -c ../../../src/cairn/utils/arguments.cpp -o ../../../.install/obj/arguments_9a8dee51f130cf79.o

t_17: t_45 t_59 t_53| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/type_traits_0.~hdr.pcm -fmodule-file=../../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../../.install/pcm/filesystem_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -xc++-module --precompile ../../../src/cairn/utils/serialization_rules.cpp -o ../../../.install/pcm/cairn.utils.serializer.rules.pcm
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/type_traits_0.~hdr.pcm -fmodule-file=../../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../../.install/pcm/filesystem_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -c ../../../src/cairn/utils/serialization_rules.cpp -o ../../../.install/obj/serialization_rules_9a8dee51f130cf79.o

t_18: t_76 t_27 t_71 t_11 t_49 t_7 t_8| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/atomic_0.~hdr.pcm -fmodule-file=../../.install/pcm/mutex_0.~hdr.pcm -fmodule-file=../../.install/pcm/memory_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -xc++-module --precompile ../../src/cairn/builder.cpp -o ../../.install/pcm/cairn.builder.pcm
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/atomic_0.~hdr.pcm -fmodule-file=../../.install/pcm/mutex_0.~hdr.pcm -fmodule-file=../../.install/pcm/memory_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -c ../../src/cairn/builder.cpp -o ../../.install/obj/builder_f4ce731b09f65819.o

t_19: t_55| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/string_view_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -xc++-module --precompile ../../src/cairn/module_type.cpp -o ../../.install/pcm/cairn.module_type.pcm
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/string_view_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -c ../../src/cairn/module_type.cpp -o ../../.install/obj/module_type_f4ce731b09f65819.o

t_20: t_68 t_73 t_79 t_48 t_61 t_50 t_54 t_34 t_59 t_23 t_56 t_14 t_4 t_8 t_15 t_27 t_16 t_17 t_1 t_12 t_10 t_33 t_29 t_36 t_53 t_19| workdir 
	cd src/cairn/compilers/msvc; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../../.install/pcm/unordered_map_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/span_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/numeric_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/map_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/format_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/iostream_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/fstream_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/filesystem_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../../.install/pcm -c ../../../../src/cairn/compilers/msvc/compiler_msvc.cpp -o ../../../../.install/obj/compiler_msvc_d52495085800088b.o

t_21: t_56 t_62 t_71 t_50 t_27| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../../.install/pcm/functional_0.~hdr.pcm -fmodule-file=../../../.install/pcm/mutex_0.~hdr.pcm -fmodule-file=../../../.install/pcm/iostream_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -c ../../../src/cairn/utils/log.cpp -o ../../../.install/obj/log_9a8dee51f130cf79.o

t_22: t_80 t_61 t_59 t_63 t_57 t_68 t_56 t_64 t_65 t_4| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/charconv_0.~hdr.pcm -fmodule-file=../../../.install/pcm/format_0.~hdr.pcm -fmodule-file=../../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../../.install/pcm/algorithm_0.~hdr.pcm -fmodule-file=../../../.install/pcm/optional_0.~hdr.pcm -fmodule-file=../../../.install/pcm/unordered_map_0.~hdr.pcm -fmodule-file=../../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../../.install/pcm/exception_0.~hdr.pcm -fmodule-file=../../../.install/pcm/variant_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -xc++-module --precompile ../../../src/cairn/utils/simple_json.cpp -o ../../../.install/pcm/cairn.utils.simple_json.pcm
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/charconv_0.~hdr.pcm -fmodule-file=../../../.install/pcm/format_0.~hdr.pcm -fmodule-file=../../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../../.install/pcm/algorithm_0.~hdr.pcm -fmodule-file=../../../.install/pcm/optional_0.~hdr.pcm -fmodule-file=../../../.install/pcm/unordered_map_0.~hdr.pcm -fmodule-file=../../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../../.install/pcm/exception_0.~hdr.pcm -fmodule-file=../../../.install/pcm/variant_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -c ../../../src/cairn/utils/simple_json.cpp -o ../../../.install/obj/simple_json_9a8dee51f130cf79.o

t_23: t_49 t_8| workdir 
	cd src/cairn/compilers/msvc; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../../.install/pcm/memory_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../../.install/pcm -xc++-module --precompile ../../../../src/cairn/compilers/msvc/factory.cpp -o ../../../../.install/pcm/cairn.compiler.msvc.pcm
	cd src/cairn/compilers/msvc; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../../.install/pcm/memory_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../../.install/pcm -c ../../../../src/cairn/compilers/msvc/factory.cpp -o ../../../../.install/obj/factory_d52495085800088b.o

t_24: t_56 t_81| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../../.install/pcm/streambuf_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -xc++-module --precompile ../../../src/cairn/utils/fd_streambuf.cpp -o ../../../.install/pcm/cairn.utils.fd_streambuf.pcm
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../../.install/pcm/streambuf_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -c ../../../src/cairn/utils/fd_streambuf.cpp -o ../../../.install/obj/fd_streambuf_9a8dee51f130cf79.o

t_25: t_61 t_73 t_77 t_54 t_49 t_50 t_37 t_14 t_34 t_29 t_78 t_16 t_64 t_82 t_27 t_4 t_9 t_12 t_76 t_15 t_8 t_39 t_7 t_33 t_46 t_10 t_36 t_53 t_19| workdir 
	cd src/cairn/compilers/gcc; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../../.install/pcm/format_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/span_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/array_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/fstream_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/memory_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/iostream_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/unordered_set_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/exception_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/regex_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/atomic_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/stdexcept_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/filesystem_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../../.install/pcm -c ../../../../src/cairn/compilers/gcc/compiler_gcc.cpp -o ../../../../.install/obj/compiler_gcc_4b9f900a6746ec2b.o

t_26: t_53 t_56 t_38 t_10| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -xc++-module --precompile ../../src/cairn/module_resolver.ifc.cpp -o ../../.install/pcm/cairn.module_resolver.pcm
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -c ../../src/cairn/module_resolver.ifc.cpp -o ../../.install/obj/module_resolver.ifc_f4ce731b09f65819.o

t_27: t_45 t_62 t_77 t_56 t_61| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/type_traits_0.~hdr.pcm -fmodule-file=../../../.install/pcm/functional_0.~hdr.pcm -fmodule-file=../../../.install/pcm/array_0.~hdr.pcm -fmodule-file=../../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../../.install/pcm/format_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -xc++-module --precompile ../../../src/cairn/utils/log.ifc.cpp -o ../../../.install/pcm/cairn.utils.log.pcm
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/type_traits_0.~hdr.pcm -fmodule-file=../../../.install/pcm/functional_0.~hdr.pcm -fmodule-file=../../../.install/pcm/array_0.~hdr.pcm -fmodule-file=../../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../../.install/pcm/format_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -c ../../../src/cairn/utils/log.ifc.cpp -o ../../../.install/obj/log.ifc_9a8dee51f130cf79.o

t_28: t_61 t_83 t_70 t_67 t_13 t_19 t_26 t_0 t_33 t_78 t_17 t_16 t_29 t_27 t_15 t_76 t_8 t_1| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/format_0.~hdr.pcm -fmodule-file=../../.install/pcm/ranges_0.~hdr.pcm -fmodule-file=../../.install/pcm/queue_0.~hdr.pcm -fmodule-file=../../.install/pcm/ostream_0.~hdr.pcm -fmodule-file=../../.install/pcm/unordered_set_0.~hdr.pcm -fmodule-file=../../.install/pcm/atomic_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -c ../../src/cairn/module_database.cpp -o ../../.install/obj/module_database_f4ce731b09f65819.o

t_29: t_22 t_0 t_65 t_68 t_56 t_16 t_53| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/variant_0.~hdr.pcm -fmodule-file=../../.install/pcm/unordered_map_0.~hdr.pcm -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -xc++-module --precompile ../../src/cairn/compile_commands_supp.ifc.cpp -o ../../.install/pcm/cairn.compile_commands.pcm
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/variant_0.~hdr.pcm -fmodule-file=../../.install/pcm/unordered_map_0.~hdr.pcm -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -c ../../src/cairn/compile_commands_supp.ifc.cpp -o ../../.install/obj/compile_commands_supp.ifc_f4ce731b09f65819.o

t_30: t_61 t_68 t_57 t_73 t_77 t_49 t_54 t_37 t_14 t_63 t_7 t_33 t_29 t_16 t_82 t_74 t_27 t_4 t_36 t_53 t_19 t_12 t_15 t_8 t_39 t_46 t_10 t_2 t_34| workdir 
	cd src/cairn/compilers/clang; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../../.install/pcm/format_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/unordered_map_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/optional_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/span_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/array_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/memory_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/fstream_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/algorithm_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/regex_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/iterator_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/filesystem_0.~hdr.pcm -fmodule-file=../../../../.install/pcm/stdexcept_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../../.install/pcm -c ../../../../src/cairn/compilers/clang/compiler_clang.cpp -o ../../../../.install/obj/compiler_clang_2f01e9763865527e.o

t_31: t_43 t_45| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/utility_0.~hdr.pcm -fmodule-file=../../../.install/pcm/type_traits_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -xc++-module --precompile ../../../src/cairn/utils/function_view.cpp -o ../../../.install/pcm/cairn.utils.function_view.pcm
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/utility_0.~hdr.pcm -fmodule-file=../../../.install/pcm/type_traits_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -c ../../../src/cairn/utils/function_view.cpp -o ../../../.install/obj/function_view_9a8dee51f130cf79.o

t_32: t_56 t_55 t_68 t_47 t_54 t_4 t_53 t_16 t_59 t_11 t_73 t_48 t_13| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../.install/pcm/string_view_0.~hdr.pcm -fmodule-file=../../.install/pcm/unordered_map_0.~hdr.pcm -fmodule-file=../../.install/pcm/set_0.~hdr.pcm -fmodule-file=../../.install/pcm/fstream_0.~hdr.pcm -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -fmodule-file=../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../.install/pcm/span_0.~hdr.pcm -fmodule-file=../../.install/pcm/map_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -xc++-module --precompile ../../src/cairn/script_build.cpp -o ../../.install/pcm/cairn.script_build.pcm
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../.install/pcm/string_view_0.~hdr.pcm -fmodule-file=../../.install/pcm/unordered_map_0.~hdr.pcm -fmodule-file=../../.install/pcm/set_0.~hdr.pcm -fmodule-file=../../.install/pcm/fstream_0.~hdr.pcm -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -fmodule-file=../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../.install/pcm/span_0.~hdr.pcm -fmodule-file=../../.install/pcm/map_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -c ../../src/cairn/script_build.cpp -o ../../.install/obj/script_build_f4ce731b09f65819.o

t_33: t_53 t_19| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -xc++-module --precompile ../../src/cairn/source_def.cpp -o ../../.install/pcm/cairn.source_def.pcm
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -c ../../src/cairn/source_def.cpp -o ../../.install/obj/source_def_f4ce731b09f65819.o

t_34: t_56 t_48 t_59 t_84 t_60| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../../.install/pcm/map_0.~hdr.pcm -fmodule-file=../../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../../.install/pcm/cwctype_0.~hdr.pcm -fmodule-file=../../../.install/pcm/system_error_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -xc++-module --precompile ../../../src/cairn/utils/env.cpp -o ../../../.install/pcm/cairn.utils.env.pcm
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../../.install/pcm/map_0.~hdr.pcm -fmodule-file=../../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../../.install/pcm/cwctype_0.~hdr.pcm -fmodule-file=../../../.install/pcm/system_error_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -c ../../../src/cairn/utils/env.cpp -o ../../../.install/obj/env_9a8dee51f130cf79.o

t_35: t_55| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/string_view_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -xc++-module --precompile ../../src/cairn/version.cpp -o ../../.install/pcm/cairn.version.pcm
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/string_view_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -c ../../src/cairn/version.cpp -o ../../.install/obj/version_f4ce731b09f65819.o

t_36: t_50 t_49 t_16 t_53 t_46 t_24 t_34 t_56 t_27 t_44 t_73 t_57 t_79 t_85 t_60 t_59 t_86| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/iostream_0.~hdr.pcm -fmodule-file=../../../.install/pcm/memory_0.~hdr.pcm -fmodule-file=../../../.install/pcm/filesystem_0.~hdr.pcm -fmodule-file=../../../.install/pcm/stdexcept_0.~hdr.pcm -fmodule-file=../../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../../.install/pcm/cstddef_0.~hdr.pcm -fmodule-file=../../../.install/pcm/span_0.~hdr.pcm -fmodule-file=../../../.install/pcm/optional_0.~hdr.pcm -fmodule-file=../../../.install/pcm/numeric_0.~hdr.pcm -fmodule-file=../../../.install/pcm/cerrno_0.~hdr.pcm -fmodule-file=../../../.install/pcm/system_error_0.~hdr.pcm -fmodule-file=../../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../../.install/pcm/cstring_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -xc++-module --precompile ../../../src/cairn/utils/process_posix.cpp -o ../../../.install/pcm/cairn.utils.process-posix.pcm
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/iostream_0.~hdr.pcm -fmodule-file=../../../.install/pcm/memory_0.~hdr.pcm -fmodule-file=../../../.install/pcm/filesystem_0.~hdr.pcm -fmodule-file=../../../.install/pcm/stdexcept_0.~hdr.pcm -fmodule-file=../../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../../.install/pcm/cstddef_0.~hdr.pcm -fmodule-file=../../../.install/pcm/span_0.~hdr.pcm -fmodule-file=../../../.install/pcm/optional_0.~hdr.pcm -fmodule-file=../../../.install/pcm/numeric_0.~hdr.pcm -fmodule-file=../../../.install/pcm/cerrno_0.~hdr.pcm -fmodule-file=../../../.install/pcm/system_error_0.~hdr.pcm -fmodule-file=../../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../../.install/pcm/cstring_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -c ../../../src/cairn/utils/process_posix.cpp -o ../../../.install/obj/process_posix_9a8dee51f130cf79.o

t_37: t_73 t_59 t_76 t_68 t_57 t_56 t_12 t_36 t_53 t_16 t_7 t_4 t_14| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/span_0.~hdr.pcm -fmodule-file=../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../.install/pcm/atomic_0.~hdr.pcm -fmodule-file=../../.install/pcm/unordered_map_0.~hdr.pcm -fmodule-file=../../.install/pcm/optional_0.~hdr.pcm -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -xc++-module --precompile ../../src/cairn/gnu_compiler_setup.cpp -o ../../.install/pcm/cairn.gnu_compiler_setup.pcm
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/span_0.~hdr.pcm -fmodule-file=../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../.install/pcm/atomic_0.~hdr.pcm -fmodule-file=../../.install/pcm/unordered_map_0.~hdr.pcm -fmodule-file=../../.install/pcm/optional_0.~hdr.pcm -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -c ../../src/cairn/gnu_compiler_setup.cpp -o ../../.install/obj/gnu_compiler_setup_f4ce731b09f65819.o

t_38: t_53| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -xc++-module --precompile ../../src/cairn/compile_target.cpp -o ../../.install/pcm/cairn.compile_target.pcm
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -c ../../src/cairn/compile_target.cpp -o ../../.install/obj/compile_target_f4ce731b09f65819.o

t_39: t_59 t_56 t_66| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../../.install/pcm/sstream_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -xc++-module --precompile ../../../src/cairn/utils/version.cpp -o ../../../.install/pcm/cairn.utils.version.pcm
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../../.install/pcm/string_0.~hdr.pcm -fmodule-file=../../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../../.install/pcm/sstream_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../../.install/pcm -c ../../../src/cairn/utils/version.cpp -o ../../../.install/obj/version_9a8dee51f130cf79.o

t_40: t_54 t_43 t_70 t_14| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/fstream_0.~hdr.pcm -fmodule-file=../../.install/pcm/utility_0.~hdr.pcm -fmodule-file=../../.install/pcm/queue_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -c ../../src/cairn/preprocess.cpp -o ../../.install/obj/preprocess_f4ce731b09f65819.o

t_41: t_61 t_72 t_50 t_19 t_13 t_27 t_64 t_23 t_60 t_15 t_10 t_11 t_16 t_53 t_78 t_9 t_8 t_7 t_32 t_63 t_18 t_6 t_29 t_4 t_26 t_2 t_56 t_77 t_49 t_68 t_54 t_48| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -fmodule-file=../../.install/pcm/format_0.~hdr.pcm -fmodule-file=../../.install/pcm/thread_0.~hdr.pcm -fmodule-file=../../.install/pcm/iostream_0.~hdr.pcm -fmodule-file=../../.install/pcm/exception_0.~hdr.pcm -fmodule-file=../../.install/pcm/system_error_0.~hdr.pcm -fmodule-file=../../.install/pcm/filesystem_0.~hdr.pcm -fmodule-file=../../.install/pcm/unordered_set_0.~hdr.pcm -fmodule-file=../../.install/pcm/algorithm_0.~hdr.pcm -fmodule-file=../../.install/pcm/vector_0.~hdr.pcm -fmodule-file=../../.install/pcm/array_0.~hdr.pcm -fmodule-file=../../.install/pcm/memory_0.~hdr.pcm -fmodule-file=../../.install/pcm/unordered_map_0.~hdr.pcm -fmodule-file=../../.install/pcm/fstream_0.~hdr.pcm -fmodule-file=../../.install/pcm/map_0.~hdr.pcm -Wno-experimental-header-units -fprebuilt-module-path=../../.install/pcm -c ../../src/cairn/main.cpp -o ../../.install/obj/main_f4ce731b09f65819.o

t_42: t_0 t_1 t_2 t_3 t_4 t_5 t_6 t_7 t_8 t_9 t_10 t_11 t_12 t_13 t_14 t_15 t_16 t_17 t_18 t_19 t_20 t_21 t_22 t_23 t_24 t_25 t_26 t_27 t_28 t_29 t_30 t_31 t_32 t_33 t_34 t_35 t_36 t_37 t_38 t_39 t_40 t_41| workdir 
	cd .install; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG ../.install/obj/main_f4ce731b09f65819.o ../.install/obj/preprocess_f4ce731b09f65819.o ../.install/obj/compile_target_f4ce731b09f65819.o ../.install/obj/gnu_compiler_setup_f4ce731b09f65819.o ../.install/obj/process_posix_9a8dee51f130cf79.o ../.install/obj/function_view_9a8dee51f130cf79.o ../.install/obj/version_9a8dee51f130cf79.o ../.install/obj/log.ifc_9a8dee51f130cf79.o ../.install/obj/compile_commands_supp.ifc_f4ce731b09f65819.o ../.install/obj/module_resolver.ifc_f4ce731b09f65819.o ../.install/obj/compiler_gcc_4b9f900a6746ec2b.o ../.install/obj/module_database_f4ce731b09f65819.o ../.install/obj/fd_streambuf_9a8dee51f130cf79.o ../.install/obj/simple_json_9a8dee51f130cf79.o ../.install/obj/compiler_clang_2f01e9763865527e.o ../.install/obj/log_9a8dee51f130cf79.o ../.install/obj/compiler_msvc_d52495085800088b.o ../.install/obj/module_type_f4ce731b09f65819.o ../.install/obj/builder_f4ce731b09f65819.o ../.install/obj/serialization_rules_9a8dee51f130cf79.o ../.install/obj/arguments_9a8dee51f130cf79.o ../.install/obj/source_def_f4ce731b09f65819.o ../.install/obj/scanner_f4ce731b09f65819.o ../.install/obj/preprocess.ifc_f4ce731b09f65819.o ../.install/obj/process_9a8dee51f130cf79.o ../.install/obj/build_plan_f4ce731b09f65819.o ../.install/obj/factory_4b9f900a6746ec2b.o ../.install/obj/env_9a8dee51f130cf79.o ../.install/obj/abstract_compiler_f4ce731b09f65819.o ../.install/obj/factory_d52495085800088b.o ../.install/obj/module_database.ifc_f4ce731b09f65819.o ../.install/obj/thread_pool_9a8dee51f130cf79.o ../.install/obj/cli_f4ce731b09f65819.o ../.install/obj/compile_commands_supp_f4ce731b09f65819.o ../.install/obj/origin_env_f4ce731b09f65819.o ../.install/obj/utf_8_9a8dee51f130cf79.o ../.install/obj/module_resolver_f4ce731b09f65819.o ../.install/obj/script_build_f4ce731b09f65819.o ../.install/obj/factory_2f01e9763865527e.o ../.install/obj/serializer_9a8dee51f130cf79.o ../.install/obj/version_f4ce731b09f65819.o ../.install/obj/hash_9a8dee51f130cf79.o -o ../.install/cairn

t_43:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile utility -o ../../.install/pcm/utility_0.~hdr.pcm

t_44:| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile cstddef -o ../../../.install/pcm/cstddef_0.~hdr.pcm

t_45:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile type_traits -o ../../.install/pcm/type_traits_0.~hdr.pcm

t_46:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile stdexcept -o ../../.install/pcm/stdexcept_0.~hdr.pcm

t_47:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile set -o ../../.install/pcm/set_0.~hdr.pcm

t_48:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile map -o ../../.install/pcm/map_0.~hdr.pcm

t_49:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile memory -o ../../.install/pcm/memory_0.~hdr.pcm

t_50:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile iostream -o ../../.install/pcm/iostream_0.~hdr.pcm

t_51:| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile cstdint -o ../../../.install/pcm/cstdint_0.~hdr.pcm

t_52:| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile concepts -o ../../../.install/pcm/concepts_0.~hdr.pcm

t_53:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile filesystem -o ../../.install/pcm/filesystem_0.~hdr.pcm

t_54:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile fstream -o ../../.install/pcm/fstream_0.~hdr.pcm

t_55:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile string_view -o ../../.install/pcm/string_view_0.~hdr.pcm

t_56:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile vector -o ../../.install/pcm/vector_0.~hdr.pcm

t_57:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile optional -o ../../.install/pcm/optional_0.~hdr.pcm

t_58:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile cctype -o ../../.install/pcm/cctype_0.~hdr.pcm

t_59:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile string -o ../../.install/pcm/string_0.~hdr.pcm

t_60:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile system_error -o ../../.install/pcm/system_error_0.~hdr.pcm

t_61:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile format -o ../../.install/pcm/format_0.~hdr.pcm

t_62:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile functional -o ../../.install/pcm/functional_0.~hdr.pcm

t_63:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile algorithm -o ../../.install/pcm/algorithm_0.~hdr.pcm

t_64:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile exception -o ../../.install/pcm/exception_0.~hdr.pcm

t_65:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile variant -o ../../.install/pcm/variant_0.~hdr.pcm

t_66:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile sstream -o ../../.install/pcm/sstream_0.~hdr.pcm

t_67:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile ostream -o ../../.install/pcm/ostream_0.~hdr.pcm

t_68:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile unordered_map -o ../../.install/pcm/unordered_map_0.~hdr.pcm

t_69:| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile condition_variable -o ../../../.install/pcm/condition_variable_0.~hdr.pcm

t_70:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile queue -o ../../.install/pcm/queue_0.~hdr.pcm

t_71:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile mutex -o ../../.install/pcm/mutex_0.~hdr.pcm

t_72:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile thread -o ../../.install/pcm/thread_0.~hdr.pcm

t_73:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile span -o ../../.install/pcm/span_0.~hdr.pcm

t_74:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile iterator -o ../../.install/pcm/iterator_0.~hdr.pcm

t_75:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile chrono -o ../../.install/pcm/chrono_0.~hdr.pcm

t_76:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile atomic -o ../../.install/pcm/atomic_0.~hdr.pcm

t_77:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile array -o ../../.install/pcm/array_0.~hdr.pcm

t_78:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile unordered_set -o ../../.install/pcm/unordered_set_0.~hdr.pcm

t_79:| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile numeric -o ../../../.install/pcm/numeric_0.~hdr.pcm

t_80:| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile charconv -o ../../../.install/pcm/charconv_0.~hdr.pcm

t_81:| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile streambuf -o ../../../.install/pcm/streambuf_0.~hdr.pcm

t_82:| workdir 
	cd src/cairn/compilers/clang; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile regex -o ../../../../.install/pcm/regex_0.~hdr.pcm

t_83:| workdir 
	cd src/cairn; ${CLANG}  -I../../src/cairn/utils -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile ranges -o ../../.install/pcm/ranges_0.~hdr.pcm

t_84:| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile cwctype -o ../../../.install/pcm/cwctype_0.~hdr.pcm

t_85:| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile cerrno -o ../../../.install/pcm/cerrno_0.~hdr.pcm

t_86:| workdir 
	cd src/cairn/utils; ${CLANG}  -Wall -Wextra -Wpedantic -std=c++20 -O3 -DNDEBUG -Xclang -fretain-comments-from-system-headers -Wno-pragma-system-header-outside-header -fmodule-header=system -xc++-system-header --precompile cstring -o ../../../.install/pcm/cstring_0.~hdr.pcm


workdir:
	mkdir -p ./.install
	mkdir -p ./.install/obj
	mkdir -p ./.install/pcm
